const KEY='notafacil_v2';
let data=JSON.parse(localStorage.getItem(KEY)||'null')||{students:[],activeStudent:null,activeCourse:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>Number.isFinite(n)?n.toFixed(1).replace('.',','):'—';
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
let modalAction=null;
function openModal(title,label,cb){$('#modalTitle').textContent=title;$('#modalLabel').textContent=label;$('#modalInput').value='';modalAction=cb;$('#modal').classList.remove('hidden');setTimeout(()=>$('#modalInput').focus(),50)}
function closeModal(){$('#modal').classList.add('hidden');modalAction=null}
$('#modalForm').addEventListener('submit',e=>{e.preventDefault();const v=$('#modalInput').value.trim();if(!v)return;modalAction?.(v);closeModal()});$('#cancelModal').onclick=closeModal;
function student(){return data.students.find(s=>s.id===data.activeStudent)}function course(){return student()?.courses.find(c=>c.id===data.activeCourse)}
function calc(c){const valid=c.evals.filter(e=>Number.isFinite(+e.grade)&&+e.grade>=1&&+e.grade<=7&&+e.weight>0);const weight=valid.reduce((a,e)=>a+(+e.weight),0);const weighted=valid.reduce((a,e)=>a+(+e.grade)*(+e.weight)/100,0);const pres=weight?weighted/(weight/100):NaN;const complete=Math.abs(weight-100)<.01;const needed=complete?(4-pres*.6)/.4:NaN;return{weight,pres,complete,needed}}
function render(){save();const s=student();$('#studentTabs').innerHTML=data.students.map(x=>`<button class="studentTab ${x.id===data.activeStudent?'active':''}" data-id="${x.id}">${esc(x.name)}</button>`).join('');$$('.studentTab').forEach(b=>b.onclick=()=>{data.activeStudent=b.dataset.id;data.activeCourse=null;render()});$('#studentArea').classList.toggle('hidden',!s);$('#heroStudent').textContent=s?s.name:'—';$('#heroSummary').textContent=s?`${s.courses.length} ramo${s.courses.length===1?'':'s'} registrado${s.courses.length===1?'':'s'}`:'Agrega un estudiante para comenzar';if(!s)return;$('#studentTitle').textContent=`Ramos de ${s.name}`;renderCourses();const c=course();$('#courseDetail').classList.toggle('hidden',!c);$('#courseGrid').classList.toggle('hidden',!!c);$('.coursesHead').classList.toggle('hidden',!!c);if(c)renderDetail(c)}
function renderCourses(){const s=student();$('#courseGrid').innerHTML=s.courses.length?s.courses.map(c=>{const x=calc(c);let need=x.complete?(x.needed<=1?'Asegurado':x.needed>7?'No alcanzable':fmt(x.needed)):'Pendiente';return `<article class="courseCard" data-id="${c.id}"><small>ASIGNATURA</small><h3>${esc(c.name)}</h3><div class="courseStats"><div class="stat"><small>Presentación</small><b>${x.complete?fmt(x.pres):'—'}</b></div><div class="stat"><small>Examen para aprobar</small><b>${need}</b></div></div></article>`}).join(''):'<div class="card"><b>Aún no hay ramos.</b><p>Agrega la primera asignatura para comenzar a registrar notas.</p></div>';$$('.courseCard').forEach(el=>el.onclick=()=>{data.activeCourse=el.dataset.id;render()})}
function renderDetail(c){$('#courseName').textContent=c.name;$('#evalRows').innerHTML=c.evals.map(e=>`<div class="evalRow" data-id="${e.id}"><input class="ename" value="${attr(e.name)}" aria-label="Evaluación"><input class="grade" type="number" min="1" max="7" step="0.1" value="${e.grade}" placeholder="1,0–7,0" aria-label="Nota"><input class="weight" type="number" min="0" max="100" step="1" value="${e.weight}" placeholder="%" aria-label="Ponderación"><span class="aporte">${e.grade&&e.weight?fmt(+e.grade*(+e.weight)/100):'—'}</span><button class="remove" type="button" aria-label="Eliminar">×</button></div>`).join('');$$('.evalRow').forEach(row=>{const e=c.evals.find(x=>x.id===row.dataset.id);row.querySelector('.ename').oninput=v=>{e.name=v.target.value;save()};row.querySelector('.grade').oninput=v=>{e.grade=v.target.value;renderDetail(c);save()};row.querySelector('.weight').oninput=v=>{e.weight=v.target.value;renderDetail(c);save()};row.querySelector('.remove').onclick=()=>{c.evals=c.evals.filter(x=>x.id!==e.id);render()}});updateResults(c)}
function updateResults(c){const x=calc(c);const pct=Math.min(100,Math.max(0,x.weight));$('#weightText').textContent=`${Math.round(x.weight)}%`;$('#weightBar').style.width=pct+'%';$('#weightMsg').textContent=x.weight>100?'La ponderación supera el 100%.':x.complete?'Ponderación completa.':`Falta ${Math.max(0,Math.round(100-x.weight))}% para completar.`;$('#presentation').textContent=x.complete?fmt(x.pres):'—';$('#presentationMsg').textContent=x.complete?'Esta nota equivale al 60% de tu nota final.':'Completa el 100% de tus evaluaciones.';let msg='Completa el 100% de tus evaluaciones.', shown='—',marker=50;if(x.complete){if(x.needed<=1){shown='1,0';msg='Incluso con un 1,0 en el examen apruebas el ramo.';marker=0}else if(x.needed>7){shown='> 7,0';msg='No es posible alcanzar 4,0 solo con el examen.';marker=100}else{shown=fmt(Math.ceil(x.needed*10)/10);msg=`Con ${shown} o más en el examen alcanzas al menos un 4,0 final.`;marker=(Math.ceil(x.needed*10)/10-1)/6*100}}$('#neededExam').textContent=shown;$('#neededMsg').textContent=msg;$('#needMarker').style.left=Math.max(0,Math.min(100,marker))+'%';simulate(c,x)}
function simulate(c,x){const ex=+$('#examSlider').value;$('#examValue').textContent=fmt(ex);if(!x.complete){$('#finalGrade').textContent='—';$('#finalStatus').textContent='Sin datos';$('#finalStatus').className='';return}const f=x.pres*.6+ex*.4;$('#finalGrade').textContent=fmt(f);$('#finalStatus').textContent=f>=4?'APROBADO':'REPROBADO';$('#finalStatus').className=f>=4?'good':'bad'}
$('#examSlider').oninput=()=>{const c=course();if(c)updateResults(c)};$('#addStudent').onclick=()=>openModal('Agregar estudiante','Nombre del estudiante',name=>{const s={id:uid(),name,courses:[]};data.students.push(s);data.activeStudent=s.id;data.activeCourse=null;render()});$('#addCourse').onclick=()=>openModal('Agregar ramo','Nombre de la asignatura',name=>{const c={id:uid(),name,evals:[{id:uid(),name:'Prueba 1',grade:'',weight:''},{id:uid(),name:'Prueba 2',grade:'',weight:''},{id:uid(),name:'Trabajo',grade:'',weight:''}]};student().courses.push(c);data.activeCourse=c.id;render()});$('#addEval').onclick=()=>{const c=course();c.evals.push({id:uid(),name:`Evaluación ${c.evals.length+1}`,grade:'',weight:''});render()};$('#backCourses').onclick=()=>{data.activeCourse=null;render()};$('#deleteCourse').onclick=()=>{if(confirm('¿Eliminar este ramo y todas sus notas?')){const s=student();s.courses=s.courses.filter(c=>c.id!==data.activeCourse);data.activeCourse=null;render()}};$('#resetAll').onclick=()=>{if(confirm('¿Borrar todos los estudiantes, ramos y notas guardadas?')){data={students:[],activeStudent:null,activeCourse:null};render()}};
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function attr(s){return esc(s)}
render();
